### ISSUE TITLE
Any setup manual for windows server

### ISSUE THREAD

**Issue by kkelan-test** [cloverstudio/Spika#4]
Hello,

Is there anything manual for install the spika server on the windows server?

thanks

**Comment by cloverstudio** [comment]
No :D 
We'll appreciate on you if you can send pull request with that.

**Comment by kkelan-test** [comment]
OK

**Comment by Hyeon-min** [comment]
Leave a comment

**Comment by Hyeon-min** [comment]
Hello,

Is there anything manual for install the spika server on the windows server?

thanks
